openapi: "3.0.0"
info:
  title: PizzaShackAPI
  description: This is a simple API for Pizza Shack online pizza delivery store.
  version: "1.0.0"
  contact:
    name: Pizza Shack Support
    email: marketing@pizzashack.com

servers:
  - url: https://localhost:9443/am/sample/pizzashack/v1/api/
    description: Production server

paths:
  /order:
    post:
      summary: Create a new order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "200":
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

  /menu:
    get:
      summary: Retrieve the menu
      operationId: getMenu
      responses:
        "200":
          description: Menu retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Menu"

  /order/{orderId}:
    parameters:
      - name: orderId
        in: path
        description: ID of the order
        required: true
        schema:
          type: string

    get:
      summary: Get order by ID
      operationId: getOrderById
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

    put:
      summary: Update an existing order
      operationId: updateOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "200":
          description: Order updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

    delete:
      summary: Delete an order
      operationId: deleteOrder
      responses:
        "204":
          description: Order deleted successfully

components:
  schemas:
    Order:
      type: object
      properties:
        orderId:
          type: string
        items:
          type: array
          items:
            type: string
        total:
          type: number
      required:
        - orderId
        - items

    Menu:
      type: object
      properties:
        pizzas:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              price:
                type: number
      required:
        - pizzas

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

    apiKeyAuth:
      type: apiKey
      in: header
      name: ApiKey

    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://localhost:9443/oauth2/authorize
          tokenUrl: https://localhost:9443/oauth2/token
          scopes: {}

security:
  - basicAuth: []
  - apiKeyAuth: []
  - oauth2: []

tags:
  - name: pizza
    description: Operations related to Pizza Shack
